train:
  batch_size: 128
  use_cuda: True
  lr: 3.0e-4
  beta: 0.9
  max_grad_norm: 2.
  epochs: 1000
  train_type: 'RGRB'
  wait_best_reward_epoch: 10
  save_model_epoch_interval: 10
  dir_name: 'D:\transformer_eua'
  device: 'cuda:0'
data:
  user_num: 300
  x_end: 0.5
  y_end: 1
  min_cov: 1
  max_cov: 1.5
  miu: 35
  sigma: 10
  data_size:
    train: 100000
    valid: 10000
    test: 10000
model:
  dropout: 0
  capacity_reward_rate: 1
  user_embedding_type: 'transformer'
  server_embedding_type: 'linear'
  need_continue: True
  continue_model_filename: 'D:\transformer_eua\03111924_server_0.5_1_user_200_miu_35_sigma_10_transformer_linear_RGRB_capa_rate_1\03122134_96.32_55.01_51.61.mdl'