train:
  batch_size: 512
  use_cuda: True
  lr: 3.0e-4
  beta: 0.9
  epochs: 1000
  train_type: 'RGRB'
  wait_best_reward_epoch: 10
  save_model_epoch_interval: 5
  dir_name: 'D:/transformer_eua'
  device: 'cuda:0'
data:
  user_num: 100
  x_end: 0.5
  y_end: 1
  min_cov: 1
  max_cov: 1.5
  miu: 35
  sigma: 10
  data_size:
    train: 100000
    valid: 10000
    test: 10000
model:
  exploration_c: 10
  capacity_reward_rate: 1
  user_embedding_type: 'transformer'
  server_embedding_type: 'linear'
  need_continue: False
  continue_model_filename: ''
