train:
  batch_size: 512
  use_cuda: True
  lr: 1.0e-4
  lr_decay: 0.96
  beta: 0.9
  epochs: 100
  train_type: 'RGRB'
  wait_best_reward_epoch: 10
  save_model_epoch_interval: 5
  dir_name: 'D:/am_drl_eua'
  device: 'cuda:0'
data:
  user_num: 500
  x_end: 0.5
  y_end: 1
  min_cov: 1
  max_cov: 1.5
  miu: 35
  sigma: 10
  data_size:
    train: 100000
    valid: 10000
    test: 10000
model:
  hidden_dim: 256
  transformer_n_heads: 8
  transformer_n_layers: 3
  transformer_feed_forward_hidden: 512
  exploration_c: 10
  user_scale_alpha : 0.0625
  capacity_reward_rate: 0.5
  user_embedding_type: 'transformer'
  server_embedding_type: 'linear'
  need_continue: False
  continue_model_filename: ''
